// This file is automatically generated by set-env.js
// Production configuration for Vercel and Railway
export const environment = {
    production: true,
    apiUrl: 'https://mamacycle-marketplace-production.up.railway.app/api',
    assetUrl: 'https://mamacycle-marketplace-production.up.railway.app'
};

// For debugging - log the environment
console.log('PRODUCTION ENVIRONMENT LOADED');
console.log('API URL:', environment.apiUrl);
