const fs = require('fs');
const path = require('path');

// Path to environment file
const envFilePath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');

// Production environment configuration
const productionEnv = `// This file is automatically generated by set-env.js
// Production configuration for Vercel and Railway
export const environment = {
    production: true,
    apiUrl: 'https://mamacycle-marketplace-production.up.railway.app/api',
    assetUrl: 'https://mamacycle-marketplace-production.up.railway.app'
};

// For debugging - log the environment
console.log('PRODUCTION ENVIRONMENT LOADED');
console.log('API URL:', environment.apiUrl);
`;

// Write the file
try {
  fs.writeFileSync(envFilePath, productionEnv);
  console.log('✅ Environment file written successfully to', envFilePath);
  console.log('Environment configuration set to PRODUCTION');
} catch (err) {
  console.error('❌ Error writing environment file:', err);
} 